# -*- coding: utf-8 -*-
"""Kine Skeleton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqeTSz_F6X4n-l-FP5ClnKGheBR1Th1h
"""

import pandas as pd
import matplotlib.pyplot as plt

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kagglestupid/kinetics-skeleton")

print("Path to dataset files:", path)

import pandas as pd

# The 'train' DataFrame needs to be populated from the Kinetic Skeleton Dataset.
# Please provide the path to the specific data files within the downloaded dataset.

# train['index'] = range(len(train))
# train

import os
import json
import pandas as pd

# Define the base directory where the JSON files are located
# This path is derived from the 'path' variable and the 'ls' output.
data_base_path = os.path.join(path, 'kinetics_skeleton', 'kinetics_val', '0', '0')

# List to store data from all JSON files
all_skeleton_data = []

# Iterate through each file in the directory
if os.path.exists(data_base_path):
    for filename in os.listdir(data_base_path):
        if filename.endswith('.json'):
            file_path = os.path.join(data_base_path, filename)
            try:
                with open(file_path, 'r') as f:
                    data = json.load(f)
                    all_skeleton_data.append(data)
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON from {filename}: {e}")
            except Exception as e:
                print(f"Error reading {filename}: {e}")

    if all_skeleton_data:
        # Convert the list of dictionaries into a pandas DataFrame
        # Depending on the structure of the JSON, further flattening might be needed.
        train = pd.DataFrame(all_skeleton_data)
        print(f"Successfully loaded {len(all_skeleton_data)} JSON files into 'train' DataFrame.")
        display(train.head())
    else:
        print("No JSON data found to load into 'train' DataFrame.")
else:
    print(f"Error: Directory not found at {data_base_path}")

# Display the structure of the first entry in the 'data' column
if not train.empty and 'data' in train.columns:
    first_data_entry = train['data'].iloc[0]
    if first_data_entry:
        # Assuming it's a list of dictionaries, display the first dictionary
        print(json.dumps(first_data_entry[0], indent=2))
    else:
        print("The 'data' column's first entry is empty.")
else:
    print("The 'train' DataFrame is empty or does not contain a 'data' column.")

"""### Inspecting a non-empty skeleton entry

Since the first frame of the first video entry had an empty `skeleton` list, let's look for a frame that *does* contain skeleton data to understand its internal structure (i.e., the `pose`, `score`, and `bbox` fields).
"""

# Find the first frame with a non-empty skeleton in the first video entry
if not train.empty and 'data' in train.columns:
    first_video_data = train['data'].iloc[0]
    found_non_empty_skeleton = False
    for frame_data in first_video_data:
        if frame_data['skeleton']:
            print(f"Found non-empty skeleton in frame_index: {frame_data['frame_index']}")
            print(json.dumps(frame_data['skeleton'][0], indent=2))
            found_non_empty_skeleton = True
            break
    if not found_non_empty_skeleton:
        print("No non-empty skeleton found in the first video's data.")
else:
    print("The 'train' DataFrame is empty or does not contain a 'data' column.")

"""### Preprocessing the `data` column

Now that we understand the structure, we need to flatten the `pose` coordinates. Each `pose` is a list of 2D coordinates `[x1, y1, x2, y2, ...]`. We will extract these coordinates for the first detected person in each frame. If no person is detected, we will fill with zeros.
"""

def extract_and_flatten_pose(data_list):
    # This function processes a single video's data (list of frames)
    processed_frames = []
    for frame_data in data_list:
        frame_index = frame_data['frame_index']
        if frame_data['skeleton']:
            # Take the first person's skeleton data if multiple are present
            first_person_skeleton = frame_data['skeleton'][0]
            pose = first_person_skeleton.get('pose', [])
            # Flatten the pose list
            # Original pose is [x1, y1, z1, x2, y2, z2, ...] (actually, it looks like just x,y in the example)
            # We'll just take the pose as is, assuming it's already flat or needs to be kept as a list
            processed_frames.append(pose)
        else:
            # If no skeleton, append an empty list or a list of zeros for padding later
            # For now, let's append an empty list, and padding will handle the length later
            processed_frames.append([])
    return processed_frames

# Apply the function to the 'data' column
# This will transform the nested JSON into a list of lists of pose coordinates for each video
train['flat_pose_data'] = train['data'].apply(extract_and_flatten_pose)

# Display the first few rows with the new 'flat_pose_data' column
display(train[['label', 'flat_pose_data']].head())

"""### Normalizing the `X_train` data

Finally, we will normalize the pose coordinates in `X_train`. This helps in ensuring that features with larger values do not dominate the learning process and can improve the performance of many machine learning algorithms.
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Reshape X_train for MinMaxScaler. It expects 2D data (samples, features).
# We need to flatten the (max_frames, max_pose_dim) part for scaling.
original_shape = X_train.shape
X_train_reshaped = X_train.reshape(-1, original_shape[2]) # Flatten frames and poses for scaler

# Initialize and apply MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train_reshaped)

# Reshape back to original 3D structure
X_train_normalized = X_train_scaled.reshape(original_shape)

print(f"X_train data normalized. Original shape: {original_shape}, Normalized shape: {X_train_normalized.shape}")

# Display a sample of the normalized data to verify
print("\nSample of normalized X_train (first frame of first video):\n", X_train_normalized[0, 0, :5])

print("\nPreprocessing complete! The data is now ready for model training.")

"""### Splitting Data into Training and Validation Sets

Before building and training any model, it's crucial to split our preprocessed data into training and validation sets. This allows us to evaluate the model's performance on unseen data and prevent overfitting.
"""

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Split the data into training and testing sets
# We'll use 80% for training and 20% for validation
X_train_split, X_val, y_train_split, y_val = train_test_split(
    X_train_normalized, y_train, test_size=0.2, random_state=42
)

# One-hot encode the labels for categorical crossentropy loss
num_classes = len(np.unique(y_train)) # Determine the number of unique classes
y_train_one_hot = to_categorical(y_train_split, num_classes=num_classes)
y_val_one_hot = to_categorical(y_val, num_classes=num_classes)

print(f"X_train_split shape: {X_train_split.shape}")
print(f"y_train_one_hot shape: {y_train_one_hot.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_val_one_hot shape: {y_val_one_hot.shape}")

"""### Building a Baseline Sequential Model (LSTM)

As a solid starting point for action recognition with sequential skeleton data, we'll implement a Long Short-Term Memory (LSTM) network. LSTMs are a type of recurrent neural network well-suited for processing sequences and capturing long-term dependencies.

This model will serve as a strong baseline, and we can later explore more advanced architectures like Mamba.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

# Define the input shape (number of frames, pose dimensions)
input_shape = (X_train_split.shape[1], X_train_split.shape[2])

# Build the LSTM model using Input layer for best practice
model = Sequential([
    Input(shape=input_shape), # Explicit Input layer
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

# Define the input shape (number of frames, pose dimensions)
input_shape = (X_train_split.shape[1], X_train_split.shape[2])

# Build the LSTM model using Input layer for best practice
model = Sequential([
    Input(shape=input_shape), # Explicit Input layer
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""### Training the Baseline LSTM Model

Now we will train the LSTM model using the preprocessed training data (`X_train_split`, `y_train_one_hot`) and validate its performance on the validation set (`X_val`, `y_val_one_hot`).
"""

history = model.fit(
    X_train_split, y_train_one_hot,
    epochs=10, # You can adjust the number of epochs
    batch_size=32,
    validation_data=(X_val, y_val_one_hot),
    verbose=1
)

print("\nTraining complete!")

# Optionally, plot training history
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()

plt.show()

"""### Understanding the Mamba Architecture

The Mamba architecture is a novel approach to sequence modeling, utilizing **State Space Models (SSMs)** with a **selective scan mechanism**. Unlike traditional RNNs (like LSTMs) or Transformers, Mamba aims to achieve high performance with linear scalability in sequence length, making it efficient for very long sequences.

Key features of Mamba include:

*   **State Space Models (SSMs):** These are a class of models that map a 1D input function or sequence to a 1D output through a hidden state, often described by linear ordinary differential equations. Mamba adapts these for deep learning.
*   **Selective Scan Mechanism:** This is the core innovation. It allows the model to selectively propagate or ignore information along the sequence based on the input. This selectivity gives Mamba its context-awareness and efficiency, moving beyond the fixed recurrence of RNNs and the global attention of Transformers.
*   **Hardware-Aware Design:** Mamba's design is optimized for modern hardware, enabling fast computation, especially during inference.

**Implementing Mamba:**

Implementing a full Mamba model from scratch is non-trivial and often involves custom CUDA kernels and intricate state-space dynamics. Typically, Mamba is used via specialized libraries (e.g., `mamba-ssm` or `s4`). As these might require specific installation steps or a deeper dive into their API, I've provided an LSTM baseline first. If you wish to proceed with Mamba, you would generally need to:

1.  **Install a Mamba library:** e.g., `pip install mamba-ssm` (note: this often has specific PyTorch/CUDA dependencies).
2.  **Integrate Mamba blocks:** Replace or augment parts of a neural network with Mamba layers.

Let me know if you would like to explore installing and using a Mamba-specific library or if you'd like to proceed with training the LSTM model we've just defined.

### Installing Mamba Library

Implementing Mamba layers often requires a specialized library. We'll attempt to install `mamba-ssm`. Note that this library is primarily developed for PyTorch, and direct, drop-in TensorFlow/Keras Mamba layers might require a custom implementation or a different library. However, this installation will demonstrate the general approach and provide the underlying components if you wish to adapt them.

If running in Colab, ensure you have a GPU runtime, as Mamba layers are often optimized for CUDA.
"""

# Install mamba-ssm library
!pip install mamba-ssm

print("Attempted to install mamba-ssm. If there are errors related to torch/CUDA, it might indicate dependency issues or that a compatible version is not readily available for TensorFlow/Keras without custom wrappers.")



"""### Conceptual Mamba Layer in Keras

Since `mamba-ssm` is PyTorch-centric, directly importing a Keras `Mamba` layer isn't straightforward. A full Keras implementation would require building a custom layer, possibly porting parts of the `mamba-ssm` logic or using an existing Keras implementation if one is available.

Here, I'll provide a *conceptual* example of how you might structure a Keras model if a `MambaBlock` or similar layer were available. This is illustrative and won't run directly without a proper Keras Mamba layer definition.
"""

import tensorflow as tf # Import tensorflow
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling1D, Dropout

# --- Conceptual MambaBlock (THIS IS NOT A REAL IMPLEMENTATION) ---
# A placeholder for a custom Keras Mamba layer
# You would need to define a proper `tf.keras.layers.Layer` for Mamba
# This is purely for demonstration of how it would fit into a model architecture
class ConceptualMambaBlock(tf.keras.layers.Layer):
    def __init__(self, d_model, **kwargs):
        super().__init__(**kwargs)
        self.d_model = d_model
        # In a real Mamba block, you'd have SSM, selective scan, etc.
        # For this conceptual example, we'll just pass through or add a dense layer
        self.dense = tf.keras.layers.Dense(d_model, activation='relu')

    def call(self, inputs):
        return self.dense(inputs)
# --- End Conceptual MambaBlock ---

# Define the input shape
input_shape = (X_train_split.shape[1], X_train_split.shape[2]) # (timesteps, features)

# Build a conceptual Mamba model
inputs = Input(shape=input_shape)
x = ConceptualMambaBlock(d_model=64)(inputs) # Use the conceptual Mamba block
# A real Mamba model might stack multiple Mamba blocks
# x = ConceptualMambaBlock(d_model=64)(x)

# You might use pooling or another layer to get a fixed-size output for classification
x = GlobalAveragePooling1D()(x)
x = Dropout(0.3)(x)
outputs = Dense(num_classes, activation='softmax')(x)

mamba_model = Model(inputs=inputs, outputs=outputs)

mamba_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Conceptual Mamba Model Summary:")
mamba_model.summary()

print("\nNOTE: The 'ConceptualMambaBlock' used above is a placeholder and does not implement the actual Mamba architecture. A true Mamba integration would require a properly defined Keras Layer for Mamba or using a dedicated library's Keras wrapper.")

"""**Reasoning**:
To create the `SimpleSSMLayer` as requested, I need to import the `Layer` class from TensorFlow Keras and define the basic class structure.


"""

import tensorflow as tf
from tensorflow.keras.layers import Layer

class SimpleSSMLayer(Layer):
    def __init__(self, d_model, state_size, **kwargs):
        super().__init__(**kwargs)
        self.d_model = d_model
        self.state_size = state_size

    def build(self, input_shape):
        # State matrix A: (state_size, state_size)
        self.A = self.add_weight(
            shape=(self.state_size, self.state_size),
            initializer='identity',
            trainable=True,
            name='A_matrix'
        )
        # Input matrix B: (state_size, d_model)
        self.B = self.add_weight(
            shape=(self.state_size, self.d_model),
            initializer='random_normal',
            trainable=True,
            name='B_matrix'
        )
        # Output matrix C: (d_model, state_size)
        self.C = self.add_weight(
            shape=(self.d_model, self.state_size),
            initializer='random_normal',
            trainable=True,
            name='C_matrix'
        )
        # Direct feedthrough matrix D: (d_model, d_model)
        self.D = self.add_weight(
            shape=(self.d_model, self.d_model),
            initializer='identity',
            trainable=True,
            name='D_matrix'
        )
        self.built = True

    def call(self, inputs):
        # inputs shape: (batch_size, sequence_length, d_model)
        batch_size = tf.shape(inputs)[0]
        sequence_length = tf.shape(inputs)[1]

        # Initial hidden state h0
        h0 = tf.zeros((batch_size, self.state_size))

        # Define the scan function for one time step
        def scan_fn(carry, x_t):
            h_prev = carry  # h_{t-1}

            # Recurrent hidden state update: h_t = A * h_{t-1} + B * x_t
            h_t = tf.matmul(h_prev, self.A, transpose_b=True) + tf.matmul(x_t, self.B, transpose_b=True)

            # Output calculation: y_t = C * h_t + D * x_t
            y_t = tf.matmul(h_t, self.C, transpose_b=True) + tf.matmul(x_t, self.D, transpose_b=True)

            return h_t, y_t

        # Transpose inputs to (sequence_length, batch_size, d_model) for tf.scan
        # and then process each x_t in the sequence
        inputs_transposed = tf.transpose(inputs, perm=[1, 0, 2])

        # Apply tf.scan over the sequence
        _, outputs_sequence = tf.scan(
            fn=scan_fn,
            elems=inputs_transposed,
            initializer=h0
        )

        # Transpose outputs back to (batch_size, sequence_length, d_model)
        outputs = tf.transpose(outputs_sequence, perm=[1, 0, 2])
        return outputs

print("Defined SimpleSSMLayer class with build and call methods.")







pip install mamba-ssm

"""### Online Search for Keras/TensorFlow Mamba Implementations

Since I cannot directly browse the internet, please perform an online search for existing implementations of the Mamba architecture in Keras or TensorFlow. Focus on finding libraries, GitHub repositories, or research papers that provide Keras-compatible layers or models for Mamba.

Once you have completed your search, please document your findings below. Include any available code snippets, installation instructions, and potential limitations or prerequisites you discover.

---

**Your Findings:**

*   **Search Keywords Used:** (e.g., "Keras Mamba", "TensorFlow Mamba layer", "Mamba State Space Model Keras")
*   **Library/Repository Name:**
*   **Link (GitHub/Paper/Website):**
*   **Key Features/Description:** (e.g., implements selective scan, supports variable sequence lengths)
*   **Installation Instructions:** (e.g., `pip install ...`, specific dependencies)
*   **Keras/TensorFlow Compatibility:** (e.g., native Keras layer, custom wrapper, requires conversion)
*   **Limitations/Prerequisites:** (e.g., PyTorch backend, specific hardware, experimental status)
*   **Code Snippets (if any):**

```python
# Paste relevant code snippets here if found
```

### User Action Required: Online Search for Keras/TensorFlow Mamba Implementations

As an AI, I am unable to perform live online searches. To proceed with integrating a Mamba-like architecture, please perform the online search as described in the previous instructions (cell `bcec18e1`).

Once you have completed your search, please edit the `text_cell` with cell_id `bcec18e1` directly above this cell and fill out the "Your Findings Template" with the information you gather. This will allow me to understand the available options and assist you further with implementing or adapting a Mamba model in Keras/TensorFlow.

**Please ensure you fill out the template in cell `bcec18e1` before proceeding.**

### Padding `flat_pose_data` to a uniform shape

To prepare the data for machine learning, we need to ensure all sequences have the same length. This involves two levels of padding:
1.  Each frame's pose vector needs to be padded to a consistent dimension (e.g., 36).
2.  Each video (list of frames) needs to be padded to a consistent number of frames.
"""

import numpy as np

# Determine the maximum pose dimension and maximum number of frames
max_pose_dim = 0
max_frames = 0

for video_poses in train['flat_pose_data']:
    max_frames = max(max_frames, len(video_poses))
    for frame_pose in video_poses:
        max_pose_dim = max(max_pose_dim, len(frame_pose))

print(f"Maximum pose dimension found: {max_pose_dim}")
print(f"Maximum number of frames found: {max_frames}")

# Define padding function for a single video's frames
def pad_video_frames(video_poses, max_frames, max_pose_dim):
    padded_frames = []
    for frame_pose in video_poses:
        # Pad each frame's pose vector to max_pose_dim
        padded_frame_pose = np.pad(frame_pose, (0, max_pose_dim - len(frame_pose)), 'constant', constant_values=0)
        padded_frames.append(padded_frame_pose)

    # Pad the list of frames to max_frames
    while len(padded_frames) < max_frames:
        padded_frames.append(np.zeros(max_pose_dim))

    return np.array(padded_frames)

# Apply padding to all video sequences
train['padded_data'] = train['flat_pose_data'].apply(lambda x: pad_video_frames(x, max_frames, max_pose_dim))

# Display the shape of the padded data for the first few entries
print("\nShape of padded_data for the first 5 entries:")
for i in range(5):
    if i < len(train):
        print(f"Entry {i}: {train['padded_data'].iloc[i].shape}")

# Convert to a 3D numpy array if desired (all entries must have same shape)
X_train = np.array(list(train['padded_data']))
y_train = train['label_index'].values

print(f"\nShape of X_train (all padded video sequences): {X_train.shape}")
print(f"Shape of y_train (labels): {y_train.shape}")

!ls -R "{path}"